# Generated by Django 5.2 on 2025-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keycloak_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
